# Generated by Django 5.1.5 on 2025-04-19 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterDataCapacityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, max_length=250, null=True)),
                ('subversion', models.CharField(blank=True, max_length=250, null=True)),
                ('Foundry', models.CharField(blank=True, max_length=250, null=True)),
                ('PouringDaysPerWeek', models.IntegerField(blank=True, null=True)),
                ('ShiftsPerDay', models.IntegerField(blank=True, null=True)),
                ('HoursPershift', models.IntegerField(blank=True, null=True)),
                ('Maxnumberofheatsperday', models.IntegerField(blank=True, null=True)),
                ('Minnumberofheatsperday', models.IntegerField(blank=True, null=True)),
                ('Averagenumberofheatsperday', models.IntegerField(blank=True, null=True)),
                ('Month', models.DateField(blank=True, null=True)),
                ('Yiled', models.FloatField(blank=True, null=True)),
                ('Waster', models.FloatField(blank=True, null=True)),
                ('Dresspouringcapacity', models.FloatField(blank=True, null=True)),
                ('Calendardays', models.IntegerField(blank=True, null=True)),
                ('Plannedmaintenancedays', models.IntegerField(blank=True, null=True)),
                ('Publicholidays', models.IntegerField(blank=True, null=True)),
                ('Weekends', models.IntegerField(blank=True, null=True)),
                ('Othernonpouringdays', models.IntegerField(blank=True, null=True)),
                ('Unavailabiledays', models.IntegerField(blank=True, null=True)),
                ('Availabledays', models.IntegerField(blank=True, null=True)),
                ('Heatsperday', models.IntegerField(blank=True, null=True)),
                ('CastMasstonsperheat', models.FloatField(blank=True, null=True)),
                ('Casttonnesperday', models.FloatField(blank=True, null=True)),
                ('Workcentre', models.CharField(default='Pouring', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MasterDataCommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=250)),
                ('subversion', models.CharField(max_length=250)),
                ('PriorAssumptionsDecisions', models.TextField(max_length=1000)),
                ('NewAssumptions', models.TextField(max_length=1000)),
                ('Opportunities', models.TextField(max_length=1000)),
                ('Risk', models.TextField(max_length=1000)),
                ('DecisionsActionsRequired', models.TextField(max_length=1000)),
                ('SummaryKPI', models.TextField(max_length=1000)),
                ('SummaryCapacity', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='MasterDataFreightModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=250)),
                ('ForecastRegion', models.CharField(max_length=250)),
                ('ManufacturingSite', models.CharField(max_length=250)),
                ('PlantToDomesticPortDays', models.IntegerField()),
                ('OceanFreightDays', models.IntegerField()),
                ('PortToCustomerDays', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MasterDataHistoryOfProductionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=250)),
                ('Product', models.CharField(max_length=250)),
                ('Foundry', models.CharField(max_length=250)),
                ('ProductionMonth', models.DateField()),
                ('ProductionQty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MasterdataIncoTermsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=250)),
                ('CustomerCode', models.CharField(max_length=250)),
                ('Incoterm', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MasterDataIncotTermTypesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=250)),
                ('IncoTerm', models.CharField(max_length=250)),
                ('IncoTermCaregory', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MasterDataLeadTimesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=250)),
                ('Foundry', models.CharField(max_length=250)),
                ('SalesClass', models.CharField(max_length=250)),
                ('InventoryClass', models.CharField(max_length=250)),
                ('LeatTimeDays', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MasterDataOrderBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=100)),
                ('site', models.CharField(max_length=100)),
                ('productkey', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MasterDataPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Version', models.CharField(max_length=250)),
                ('SubVersion', models.CharField(max_length=250)),
                ('Foundry', models.CharField(max_length=250)),
                ('FB', models.CharField(max_length=250)),
                ('PouringDaysperweek', models.IntegerField()),
                ('CalendarDays', models.IntegerField()),
                ('Month', models.DateField()),
                ('Yield', models.FloatField()),
                ('WasterPercentage', models.FloatField()),
                ('PlanDressMass', models.FloatField()),
                ('UnavailableDays', models.IntegerField()),
                ('AvailableDays', models.IntegerField()),
                ('PlannedMaintenanceDays', models.IntegerField()),
                ('PublicHolidays', models.IntegerField()),
                ('Weekends', models.IntegerField()),
                ('OtherNonPouringDays', models.IntegerField()),
                ('HeatsPerweek', models.FloatField()),
                ('heatsperdays', models.FloatField()),
                ('CastMass', models.FloatField()),
                ('TonsPerHeat', models.FloatField()),
                ('CastTonsPerDay', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MasterDataProductAttributesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=250)),
                ('Product', models.CharField(max_length=250)),
                ('Region', models.CharField(max_length=250)),
                ('DynamicSafetyStock', models.FloatField()),
                ('StaticSafetyStock', models.FloatField()),
                ('OrderMultipleQty', models.FloatField()),
                ('MinOrderQty', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MasterDataSalesAllocationToPlantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Version', models.CharField(max_length=250)),
                ('Plant', models.CharField(max_length=250)),
                ('SalesClass', models.CharField(max_length=250)),
                ('Allocation', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MasterDataSalesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Version', models.CharField(max_length=250)),
                ('SalesClass', models.CharField(max_length=250)),
                ('GrossMargin', models.FloatField()),
                ('InHouseProduction', models.FloatField()),
                ('CostAUDPerKg', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MasterDataSKUTransferModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=250)),
                ('Product', models.CharField(max_length=250)),
                ('Date', models.DateField()),
                ('Supplier', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(max_length=100)),
                ('Product_Group', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='scenarios',
            fields=[
                ('version', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('scenario_description', models.TextField(default='type your description of this version here')),
                ('created_by', models.CharField(max_length=100)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('open_to_update', models.BooleanField(default=False)),
                ('visible_to_users', models.BooleanField(default=False)),
                ('approval1', models.BooleanField(default=False)),
                ('approval2', models.BooleanField(default=False)),
                ('approval3', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MasterDataScheduleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Version_id', models.CharField(blank=True, max_length=250, null=True)),
                ('Plant', models.CharField(blank=True, max_length=250, null=True)),
                ('SalesClass', models.CharField(blank=True, max_length=250, null=True)),
                ('ProductGroup', models.CharField(blank=True, max_length=250, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('ScheduleQty', models.FloatField(blank=True, null=True)),
                ('UnitOfMeasure', models.CharField(blank=True, max_length=250, null=True)),
                ('Scenario_Foreign_Key', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.scenarios')),
            ],
        ),
        migrations.CreateModel(
            name='MasterDataProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(max_length=250, null=True)),
                ('Weight', models.FloatField(null=True)),
                ('Grade', models.CharField(max_length=250, null=True)),
                ('ExistsInEpicor', models.BooleanField(null=True)),
                ('ProductGroup', models.CharField(max_length=250, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('Version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.scenarios')),
            ],
        ),
        migrations.CreateModel(
            name='MasterDataPlantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.CharField(max_length=250, null=True)),
                ('Country', models.CharField(max_length=250, null=True)),
                ('City', models.CharField(max_length=250, null=True)),
                ('PlantCode', models.CharField(max_length=250, null=True)),
                ('CastToDespatchDays', models.IntegerField(null=True)),
                ('version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.scenarios')),
            ],
        ),
        migrations.CreateModel(
            name='SMART_Forecast_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Forecast_Region', models.CharField(blank=True, max_length=100, null=True)),
                ('Product_Group', models.CharField(blank=True, max_length=100, null=True)),
                ('Product', models.CharField(blank=True, max_length=100, null=True)),
                ('ProductFamilyDescription', models.CharField(blank=True, max_length=100, null=True)),
                ('Customer_code', models.CharField(blank=True, max_length=100, null=True)),
                ('Location', models.CharField(blank=True, max_length=100, null=True)),
                ('Forecasted_Weight_Curr', models.FloatField(default=0, null=True)),
                ('PriceAUD', models.FloatField(default=0, null=True)),
                ('DP_Cycle', models.DateField(null=True)),
                ('Period_AU', models.DateField(null=True)),
                ('Qty', models.FloatField(default=0, null=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.scenarios')),
            ],
        ),
    ]
