# Generated by Django 5.1.5 on 2025-04-30 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatedProductionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pouring_date', models.DateField()),
                ('production_quantity', models.FloatField(default=0)),
                ('tonnes', models.FloatField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.masterdataproductmodel')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.masterdataplantmodel')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.scenarios')),
            ],
        ),
    ]
