# Generated by Django 5.1.5 on 2025-04-19 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MasterDataProductModel',
        ),
    ]
