# Generated by Django 5.0.14 on 2025-06-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdataepicorbillofmaterialmodel',
            name='ComponentSeq',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterdataepicorbillofmaterialmodel',
            name='EstimatedScrap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterdataepicorbillofmaterialmodel',
            name='SalvageQtyPer',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
