# Generated by Django 5.1.5 on 2025-05-01 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_calculatedproductionmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdatacapacitymodel',
            name='Foundry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.masterdataplantmodel'),
        ),
        migrations.AlterField(
            model_name='masterdatacapacitymodel',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.scenarios'),
        ),
        migrations.AlterField(
            model_name='masterdataplan',
            name='AvailableDays',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterdataplan',
            name='CalendarDays',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterdataplan',
            name='CastMass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterdataplan',
            name='CastTonsPerDay',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterdataplan',
            name='FB',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='masterdataplan',
            name='Foundry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.masterdataplantmodel'),
        ),
        migrations.AlterField(
            model_name='masterdataplan',
            name='HeatsPerweek',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterdataplan',
            name='Month',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterdataplan',
            name='OtherNonPouringDays',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterdataplan',
            name='PlanDressMass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterdataplan',
            name='PlannedMaintenanceDays',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterdataplan',
            name='PouringDaysperweek',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterdataplan',
            name='PublicHolidays',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterdataplan',
            name='SubVersion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='masterdataplan',
            name='TonsPerHeat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterdataplan',
            name='UnavailableDays',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterdataplan',
            name='Version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.scenarios'),
        ),
        migrations.AlterField(
            model_name='masterdataplan',
            name='WasterPercentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterdataplan',
            name='Weekends',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterdataplan',
            name='Yield',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterdataplan',
            name='heatsperdays',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
