# Generated by Django 5.1.5 on 2025-05-01 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_masterdatacapacitymodel_foundry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterdataplan',
            name='AvailableDays',
        ),
        migrations.RemoveField(
            model_name='masterdataplan',
            name='CalendarDays',
        ),
        migrations.RemoveField(
            model_name='masterdataplan',
            name='CastMass',
        ),
        migrations.RemoveField(
            model_name='masterdataplan',
            name='CastTonsPerDay',
        ),
        migrations.RemoveField(
            model_name='masterdataplan',
            name='HeatsPerweek',
        ),
        migrations.RemoveField(
            model_name='masterdataplan',
            name='PlanDressMass',
        ),
        migrations.RemoveField(
            model_name='masterdataplan',
            name='PouringDaysperweek',
        ),
        migrations.RemoveField(
            model_name='masterdataplan',
            name='UnavailableDays',
        ),
    ]
