# Generated by Django 5.1.5 on 2025-04-19 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_masterdataproductmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MasterDataProductModel',
        ),
    ]
