# Generated by Django 5.0.14 on 2025-07-09 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_smart_forecast_model_cogs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smart_forecast_model',
            name='COGS',
        ),
        migrations.RemoveField(
            model_name='smart_forecast_model',
            name='Cost_AUD',
        ),
        migrations.CreateModel(
            name='ProductSiteCostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_aud', models.FloatField(blank=True, null=True)),
                ('cost_date', models.DateField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.masterdataproductmodel')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.masterdataplantmodel')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.scenarios')),
            ],
            options={
                'unique_together': {('version', 'product', 'site')},
            },
        ),
    ]
