# Generated by Django 5.1.5 on 2025-04-19 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_delete_masterdataproductmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterDataProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(max_length=250, null=True)),
                ('Weight', models.FloatField(null=True)),
                ('Grade', models.CharField(max_length=250, null=True)),
                ('ExistsInEpicor', models.BooleanField(null=True)),
                ('ProductGroup', models.CharField(max_length=250, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('SPRversion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.scenarios')),
            ],
        ),
    ]
