# Generated by Django 5.1.5 on 2025-05-01 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_masterdataplan_availabledays_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterdataplan',
            name='FB',
        ),
        migrations.RemoveField(
            model_name='masterdataplan',
            name='SubVersion',
        ),
    ]
