# Generated by Django 5.1.5 on 2025-04-20 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_masterdataproductmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterdataproductmodel',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='masterdataproductmodel',
            name='SPRversion',
        ),
        migrations.RemoveField(
            model_name='masterdataproductmodel',
            name='Weight',
        ),
        migrations.RemoveField(
            model_name='masterdataproductmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='masterdataproductmodel',
            name='CastMass',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='masterdataproductmodel',
            name='DressMass',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='masterdataproductmodel',
            name='InventoryClass',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterdataproductmodel',
            name='InventoryClassDescription',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='masterdataproductmodel',
            name='ParentProductGroup',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterdataproductmodel',
            name='ParentProductGroupDescription',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='masterdataproductmodel',
            name='PartClassDescription',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='masterdataproductmodel',
            name='PartClassID',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterdataproductmodel',
            name='ProductDescription',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='masterdataproductmodel',
            name='ProductFamily',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterdataproductmodel',
            name='ProductFamilyDescription',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='masterdataproductmodel',
            name='ProductGroupDescription',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='masterdataproductmodel',
            name='SalesClass',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterdataproductmodel',
            name='SalesClassDescription',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='masterdataproductmodel',
            name='Product',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
