# Generated by Django 5.1.5 on 2025-05-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_masterdataplan_fb_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='masterdataplan',
            constraint=models.UniqueConstraint(fields=('Foundry', 'Month'), name='unique_foundry_month'),
        ),
    ]
