# Generated by Django 5.1.5 on 2025-05-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_masterdataplan_unique_foundry_month'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='masterdataplan',
            name='unique_foundry_month',
        ),
        migrations.AddConstraint(
            model_name='masterdataplan',
            constraint=models.UniqueConstraint(fields=('Foundry', 'Month', 'Version'), name='unique_foundry_month_version'),
        ),
    ]
