# Generated by Django 5.1.5 on 2025-04-20 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_masterdataproductmodel_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterDataProductPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(null=True, upload_to='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.masterdataproductmodel')),
            ],
        ),
    ]
