# Generated by Django 5.0.14 on 2025-07-15 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_productsitecostmodel_revenue_cost_aud'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatedproductionmodel',
            name='parent_product_group',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
