# Generated by Django 5.1.5 on 2025-04-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_masterdataproductpictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdataproductmodel',
            name='InventoryClassDescription',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='masterdataproductmodel',
            name='ParentProductGroupDescription',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='masterdataproductmodel',
            name='PartClassDescription',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='masterdataproductmodel',
            name='ProductDescription',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='masterdataproductmodel',
            name='ProductFamilyDescription',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='masterdataproductmodel',
            name='ProductGroupDescription',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='masterdataproductmodel',
            name='SalesClassDescription',
            field=models.TextField(null=True),
        ),
    ]
