# Generated by Django 5.1.5 on 2025-05-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_masterdataplan_unique_foundry_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterDataSuppliersModel',
            fields=[
                ('VendorID', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('TradingName', models.CharField(blank=True, max_length=250, null=True)),
                ('Address1', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='masterdatacustomersmodel',
            old_name='CustomerCode',
            new_name='CustomerId',
        ),
        migrations.RenameField(
            model_name='masterdatacustomersmodel',
            old_name='CustomerGroup',
            new_name='CustomerRegion',
        ),
        migrations.RenameField(
            model_name='masterdatacustomersmodel',
            old_name='ProductGroup',
            new_name='ForecastRegion',
        ),
        migrations.RemoveField(
            model_name='masterdatacustomersmodel',
            name='CustomerGroupDescription',
        ),
        migrations.RemoveField(
            model_name='masterdatacustomersmodel',
            name='ProductGroupDescription',
        ),
        migrations.RemoveField(
            model_name='masterdatacustomersmodel',
            name='SalesClass',
        ),
        migrations.RemoveField(
            model_name='masterdatacustomersmodel',
            name='SalesClassDescription',
        ),
    ]
