# Generated by Django 5.0.14 on 2025-07-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_fixedplantconversionmodifiersmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixedplantconversionmodifiersmodel',
            name='ConversionModifier',
        ),
        migrations.RemoveField(
            model_name='revenueconversionmodifiersmodel',
            name='ConversionModifier',
        ),
        migrations.AddField(
            model_name='fixedplantconversionmodifiersmodel',
            name='CostPerHourAUD',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='fixedplantconversionmodifiersmodel',
            name='CostPerSQMorKgAUD',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='fixedplantconversionmodifiersmodel',
            name='ExternalMaterialComponents',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='fixedplantconversionmodifiersmodel',
            name='FreightPercentage',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='fixedplantconversionmodifiersmodel',
            name='GrossMargin',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='fixedplantconversionmodifiersmodel',
            name='ManHourCost',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='fixedplantconversionmodifiersmodel',
            name='MaterialCostPercentage',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='revenueconversionmodifiersmodel',
            name='CostAUDPerKG',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='revenueconversionmodifiersmodel',
            name='GrossMargin',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='revenueconversionmodifiersmodel',
            name='InHouseProduction',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
