# Generated by Django 5.1.5 on 2025-05-03 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_masterdatasuppliersmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterDataSupplyOptionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InhouseOrOutsource', models.CharField(max_length=250)),
                ('SourceName', models.CharField(blank=True, max_length=250, null=True)),
                ('DateofSupply', models.DateField(blank=True, null=True)),
                ('Qty', models.FloatField(blank=True, default=0, null=True)),
                ('Tonnes', models.FloatField(blank=True, default=0, null=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.masterdataproductmodel')),
                ('Site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.masterdataplantmodel')),
                ('Supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.masterdatasuppliersmodel')),
            ],
        ),
    ]
