# Generated by Django 5.1.5 on 2025-04-20 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_masterdataproductmodel_inventoryclassdescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdataproductpictures',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.masterdataproductmodel'),
        ),
    ]
