# Generated by Django 5.1.5 on 2025-04-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_masterdataproductpictures_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdataproductmodel',
            name='SalesClass',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
