# Generated by Django 5.1.5 on 2025-05-03 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_masterdatasupplyoptionsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdatasupplyoptionsmodel',
            name='InhouseOrOutsource',
            field=models.CharField(default='Inhouse', max_length=250),
        ),
    ]
