# Generated by Django 5.1.5 on 2025-04-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_masterdataproductmodel_salesclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdataproductmodel',
            name='CastMass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterdataproductmodel',
            name='DressMass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterdataproductmodel',
            name='ExistsInEpicor',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterdataproductmodel',
            name='Grade',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='masterdataproductmodel',
            name='InventoryClass',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='masterdataproductmodel',
            name='InventoryClassDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterdataproductmodel',
            name='ParentProductGroup',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='masterdataproductmodel',
            name='ParentProductGroupDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterdataproductmodel',
            name='PartClassDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterdataproductmodel',
            name='PartClassID',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='masterdataproductmodel',
            name='ProductDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterdataproductmodel',
            name='ProductFamily',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='masterdataproductmodel',
            name='ProductFamilyDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterdataproductmodel',
            name='ProductGroup',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='masterdataproductmodel',
            name='SalesClassDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
