# Generated by Django 5.1.5 on 2025-05-03 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_masterdatasupplyoptionsmodel_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdatasupplyoptionsmodel',
            name='Site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.masterdataplantmodel'),
        ),
    ]
