# Generated by Django 5.1.5 on 2025-04-20 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_masterdataproductmodel_castmass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdataproductpictures',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.masterdataproductmodel'),
        ),
    ]
