# Generated by Django 5.1.5 on 2025-05-05 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_masterdatasupplyoptionsmodel_supplier'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='masterdataplan',
            name='unique_foundry_month_version',
        ),
        migrations.RenameField(
            model_name='masterdataplan',
            old_name='Version',
            new_name='version',
        ),
        migrations.RenameField(
            model_name='masterdatasalesallocationtoplantmodel',
            old_name='Version',
            new_name='version',
        ),
        migrations.RenameField(
            model_name='masterdatasalesmodel',
            old_name='Version',
            new_name='version',
        ),
        migrations.RenameField(
            model_name='masterdataschedulemodel',
            old_name='Scenario_Foreign_Key',
            new_name='version',
        ),
        migrations.RemoveField(
            model_name='masterdataschedulemodel',
            name='Version_id',
        ),
        migrations.AlterField(
            model_name='masterdatasupplyoptionsmodel',
            name='Site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.masterdataplantmodel'),
        ),
        migrations.AddConstraint(
            model_name='masterdataplan',
            constraint=models.UniqueConstraint(fields=('Foundry', 'Month', 'version'), name='unique_foundry_month_version'),
        ),
    ]
