# Generated by Django 5.1.5 on 2025-04-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_masterdataproductpictures_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterdataplantmodel',
            name='CastToDespatchDays',
        ),
        migrations.RemoveField(
            model_name='masterdataplantmodel',
            name='City',
        ),
        migrations.RemoveField(
            model_name='masterdataplantmodel',
            name='PlantCode',
        ),
        migrations.RemoveField(
            model_name='masterdataplantmodel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='masterdataplantmodel',
            name='plant',
        ),
        migrations.RemoveField(
            model_name='masterdataplantmodel',
            name='version',
        ),
        migrations.AddField(
            model_name='masterdataplantmodel',
            name='About',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='masterdataplantmodel',
            name='Company',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterdataplantmodel',
            name='Location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterdataplantmodel',
            name='PlantRegion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterdataplantmodel',
            name='Site',
            field=models.CharField(default='ghost', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='masterdataplantmodel',
            name='SiteType',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='masterdataplantmodel',
            name='Country',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
