# Generated by Django 5.1.5 on 2025-05-05 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_remove_masterdataplan_unique_foundry_month_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterDataEpicorSupplierMasterDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=100)),
                ('Plant', models.CharField(max_length=100)),
                ('PartNum', models.CharField(max_length=100)),
                ('VendorID', models.CharField(max_length=100)),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.scenarios')),
            ],
        ),
    ]
