# Generated by Django 5.1.5 on 2025-05-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_masterdataepicorsuppliermasterdatamodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdataepicorsuppliermasterdatamodel',
            name='Company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='masterdataepicorsuppliermasterdatamodel',
            name='PartNum',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='masterdataepicorsuppliermasterdatamodel',
            name='Plant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='masterdataepicorsuppliermasterdatamodel',
            name='VendorID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
