# Generated by Django 5.1.5 on 2025-04-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_remove_masterdataplantmodel_casttodespatchdays_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterdataplantmodel',
            name='Site',
        ),
        migrations.AddField(
            model_name='masterdataplantmodel',
            name='SiteName',
            field=models.CharField(default=1, max_length=250, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
