# Generated by Django 5.0.14 on 2025-07-22 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_masterdatasafetystocks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculatedproductionmodel',
            name='cost_aud',
        ),
    ]
