# Generated by Django 5.0.14 on 2025-07-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_remove_unused_cost_aud_from_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatedproductionmodel',
            name='cost_aud',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
