# Generated by Django 5.1.5 on 2025-05-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_masterdataepicorsuppliermasterdatamodel_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterdataepicorsuppliermasterdatamodel',
            name='SourceType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
