# Generated by Django 5.1.5 on 2025-04-22 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_remove_masterdataplantmodel_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smart_forecast_model',
            name='Data_Source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Revenue_Forecast_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_Source', models.CharField(blank=True, max_length=100, null=True)),
                ('Forecast_Region', models.CharField(blank=True, max_length=100, null=True)),
                ('ParentProductGroupDescription', models.CharField(blank=True, max_length=100, null=True)),
                ('ProductGroupDescription', models.CharField(blank=True, max_length=100, null=True)),
                ('Period_AU', models.DateField(null=True)),
                ('Revenue', models.FloatField(default=0, null=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.scenarios')),
            ],
        ),
    ]
