# Generated by Django 5.0.14 on 2025-07-23 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_restore_cost_aud_for_compatibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioOptimizationState',
            fields=[
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.scenarios')),
                ('auto_optimization_applied', models.BooleanField(default=False)),
                ('last_optimization_date', models.DateTimeField(blank=True, null=True)),
                ('last_reset_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
