# Generated by Django 5.1.5 on 2025-04-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_smart_forecast_model_data_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smart_forecast_model',
            name='Tonnes',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='smart_forecast_model',
            name='DP_Cycle',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smart_forecast_model',
            name='Period_AU',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smart_forecast_model',
            name='PriceAUD',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='smart_forecast_model',
            name='Qty',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
