# Generated by Django 5.1.5 on 2025-05-08 00:22

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_masterdataepicorsuppliermasterdatamodel_sourcetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calcualtedreplenishmentmodel',
            name='Site',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name=website.models.MasterDataPlantModel),
        ),
    ]
