# Generated by Django 5.1.5 on 2025-05-08 00:23

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_calcualtedreplenishmentmodel_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatedproductionmodel',
            name='site',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name=website.models.MasterDataPlantModel),
        ),
    ]
