# Generated by Django 5.1.5 on 2025-04-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_smart_forecast_model_tonnes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedForecastParentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('parent_product_group', models.CharField(max_length=250)),
                ('tonnes', models.FloatField(default=0)),
            ],
            options={
                'unique_together': {('period', 'parent_product_group')},
            },
        ),
    ]
