# Generated by Django 5.1.5 on 2025-04-26 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_aggregatedforecastparentgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tonnes', models.FloatField(blank=True, default=0, null=True)),
                ('customer_code', models.CharField(blank=True, max_length=100, null=True)),
                ('period', models.DateField(blank=True, null=True)),
                ('product_group_description', models.TextField(blank=True, null=True)),
                ('parent_product_group_description', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.masterdataproductmodel')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.scenarios')),
            ],
        ),
        migrations.DeleteModel(
            name='AggregatedForecastParentGroup',
        ),
    ]
