# Generated by Django 5.1.5 on 2025-05-09 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_calculatedproductionmodel_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calcualtedreplenishmentmodel',
            name='Location',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.masterdataplantmodel'),
        ),
    ]
