# Generated by Django 5.0.14 on 2025-07-23 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_cachedcontroltowerdata_cacheddetailedinventorydata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedForecastChartData',
            fields=[
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.scenarios')),
                ('by_product_group', models.JSONField(default=dict)),
                ('by_parent_group', models.JSONField(default=dict)),
                ('by_region', models.JSONField(default=dict)),
                ('by_customer', models.JSONField(default=dict)),
                ('by_data_source', models.JSONField(default=dict)),
                ('total_tonnes', models.FloatField(default=0)),
                ('total_customers', models.IntegerField(default=0)),
                ('total_periods', models.IntegerField(default=0)),
                ('calculation_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AggregatedFoundryChartData',
            fields=[
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.scenarios')),
                ('foundry_data', models.JSONField(default=dict)),
                ('site_list', models.JSONField(default=list)),
                ('total_sites', models.IntegerField(default=0)),
                ('total_production', models.FloatField(default=0)),
                ('calculation_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AggregatedInventoryChartData',
            fields=[
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.scenarios')),
                ('inventory_by_group', models.JSONField(default=dict)),
                ('monthly_trends', models.JSONField(default=dict)),
                ('total_inventory_value', models.FloatField(default=0)),
                ('total_groups', models.IntegerField(default=0)),
                ('total_products', models.IntegerField(default=0)),
                ('calculation_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
