# Generated by Django 5.1.5 on 2025-04-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_aggregatedforecast_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatedforecast',
            name='forecast_region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
