# Generated by Django 5.1.5 on 2025-05-09 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_alter_calcualtedreplenishmentmodel_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calcualtedreplenishmentmodel',
            name='Location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='calcualtedreplenishmentmodel',
            name='Site',
            field=models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.masterdataplantmodel'),
        ),
        migrations.AlterField(
            model_name='calculatedproductionmodel',
            name='site',
            field=models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.masterdataplantmodel'),
        ),
    ]
