# Generated by Django 5.1.5 on 2025-05-21 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_alter_calcualtedreplenishmentmodel_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterdataplantmodel',
            name='InhouseOrOutsource',
            field=models.CharField(blank=True, default='Inhouse', max_length=250, null=True),
        ),
    ]
