# Generated by Django 5.1.5 on 2025-04-26 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_aggregatedforecast_forecast_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdataorderbook',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.scenarios'),
        ),
    ]
