# Generated by Django 5.1.5 on 2025-04-27 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_alter_masterdataorderbook_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdatahistoryofproductionmodel',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.scenarios'),
        ),
    ]
