# Generated by Django 5.1.5 on 2025-05-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_masterdataplantmodel_inhouseoroutsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterdataplantmodel',
            name='TradingName',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
