# Generated by Django 5.1.5 on 2025-04-27 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_alter_masterdatahistoryofproductionmodel_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterDataInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_snapshot', models.DateField()),
                ('product', models.CharField(max_length=250)),
                ('site', models.CharField(max_length=250)),
                ('site_region', models.CharField(max_length=250)),
                ('onhandstock_qty', models.FloatField(default=0)),
                ('intransitstock_qty', models.FloatField(default=0)),
                ('wip_stock_qty', models.FloatField(default=0)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.scenarios')),
            ],
        ),
    ]
