# Generated by Django 5.1.5 on 2025-05-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_masterdataplantmodel_tradingname'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterDataEpicorBillOfMaterialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(blank=True, max_length=100, null=True)),
                ('Plant', models.CharField(blank=True, max_length=100, null=True)),
                ('Parent', models.CharField(blank=True, max_length=100, null=True)),
                ('ComponentSeq', models.IntegerField(blank=True, max_length=100, null=True)),
                ('Component', models.CharField(blank=True, max_length=100, null=True)),
                ('ComponentUOM', models.CharField(blank=True, max_length=100, null=True)),
                ('QtyPer', models.CharField(blank=True, max_length=100, null=True)),
                ('EstimatedScrap', models.FloatField(blank=True, max_length=100, null=True)),
                ('SalvageQtyPer', models.FloatField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
