# Generated by Django 5.1.5 on 2025-04-27 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_masterdatainventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdatainventory',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.masterdataplantmodel'),
        ),
    ]
