# Generated by Django 5.1.5 on 2025-05-26 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_masterdataepicorbillofmaterialmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterDataManuallyAssignProductionRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShippingDate', models.DateField(blank=True, null=True)),
                ('Percentage', models.FloatField(blank=True, default=0, null=True)),
                ('Product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.masterdataproductmodel')),
                ('Site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.masterdataplantmodel')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.scenarios')),
            ],
        ),
    ]
