# Generated by Django 5.1.5 on 2025-04-28 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_alter_masterdatainventory_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterDataForecastRegionModel',
            fields=[
                ('Forecast_region', models.CharField(max_length=250, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='masterdatafreightmodel',
            name='ManufacturingSite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.masterdataplantmodel'),
        ),
        migrations.AlterField(
            model_name='masterdatafreightmodel',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.scenarios'),
        ),
        migrations.AlterField(
            model_name='masterdatafreightmodel',
            name='ForecastRegion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.masterdataforecastregionmodel'),
        ),
    ]
