# Generated by Django 5.0.14 on 2025-08-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_remove_aggregatedfoundrychartdata_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterdataplantmodel',
            name='mark_as_outsource_supplier',
            field=models.BooleanField(default=False, help_text='Mark this plant as an outsource supplier'),
        ),
    ]
