# Generated by Django 5.1.5 on 2025-04-28 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_masterdataforecastregionmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterDataCustomersModel',
            fields=[
                ('CustomerCode', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(blank=True, max_length=250, null=True)),
                ('CustomerGroup', models.CharField(blank=True, max_length=250, null=True)),
                ('CustomerGroupDescription', models.TextField(blank=True, null=True)),
                ('SalesClass', models.CharField(blank=True, max_length=250, null=True)),
                ('SalesClassDescription', models.TextField(blank=True, null=True)),
                ('ProductGroup', models.CharField(blank=True, max_length=250, null=True)),
                ('ProductGroupDescription', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
