# Generated by Django 5.1.5 on 2025-04-28 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_masterdatacustomersmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterDataCastToDespatchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CastToDespatchDays', models.IntegerField()),
                ('Foundry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.masterdataplantmodel')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.scenarios')),
            ],
        ),
    ]
