# Generated by Django 5.0.14 on 2025-08-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_masterdatacustomersmodel_created_by_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterdataepicorbillofmaterialmodel',
            name='created_by_user',
            field=models.CharField(blank=True, help_text='Username who created this record manually', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='masterdataepicorbillofmaterialmodel',
            name='is_user_created',
            field=models.BooleanField(default=False, help_text='True if this record was created manually by user'),
        ),
        migrations.AddField(
            model_name='masterdataepicorbillofmaterialmodel',
            name='last_imported_from_epicor',
            field=models.DateTimeField(blank=True, help_text='Last time this record was updated from Epicor', null=True),
        ),
        migrations.AddField(
            model_name='masterdataepicorbillofmaterialmodel',
            name='last_modified_by_user',
            field=models.CharField(blank=True, help_text='Username who last modified this record', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='masterdataepicorbillofmaterialmodel',
            name='last_user_modification_date',
            field=models.DateTimeField(blank=True, help_text='When user last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='masterdataepicorbillofmaterialmodel',
            name='user_modified_fields',
            field=models.JSONField(default=dict, help_text='Track which fields were modified by users'),
        ),
        migrations.AddField(
            model_name='masterdataepicormethodofmanufacturingmodel',
            name='created_by_user',
            field=models.CharField(blank=True, help_text='Username who created this record manually', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='masterdataepicormethodofmanufacturingmodel',
            name='is_user_created',
            field=models.BooleanField(default=False, help_text='True if this record was created manually by user'),
        ),
        migrations.AddField(
            model_name='masterdataepicormethodofmanufacturingmodel',
            name='last_imported_from_epicor',
            field=models.DateTimeField(blank=True, help_text='Last time this record was updated from Epicor', null=True),
        ),
        migrations.AddField(
            model_name='masterdataepicormethodofmanufacturingmodel',
            name='last_modified_by_user',
            field=models.CharField(blank=True, help_text='Username who last modified this record', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='masterdataepicormethodofmanufacturingmodel',
            name='last_user_modification_date',
            field=models.DateTimeField(blank=True, help_text='When user last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='masterdataepicormethodofmanufacturingmodel',
            name='user_modified_fields',
            field=models.JSONField(default=dict, help_text='Track which fields were modified by users'),
        ),
    ]
