# Generated by Django 5.0.14 on 2025-08-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_masterdataepicorbillofmaterialmodel_created_by_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatedproductionmodel',
            name='is_outsourced',
            field=models.BooleanField(default=False, help_text='True if this production is from an outsourced site'),
        ),
    ]
