# Generated by Django 5.0.14 on 2025-08-05 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_calculatedproductionmodel_is_outsourced'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptedQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(help_text='Product identifier', max_length=250)),
                ('purchased_qty', models.FloatField(help_text='Transaction Qty from PowerBI')),
                ('purchased_tonnes', models.FloatField(help_text='Transaction Qty * Dress Mass')),
                ('month_of_supply', models.DateField(help_text='Month of supply (grouped by month)')),
                ('receipt_date', models.DateField(help_text='Original receipt date')),
                ('dress_mass', models.FloatField(blank=True, help_text='Dress mass from product', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(help_text='Supplier (VendorID from PowerBI)', on_delete=django.db.models.deletion.CASCADE, to='website.masterdataplantmodel')),
            ],
            options={
                'verbose_name': 'Receipted Quantity',
                'verbose_name_plural': 'Receipted Quantities',
                'ordering': ['-month_of_supply', 'supplier'],
                'indexes': [models.Index(fields=['supplier', 'month_of_supply'], name='website_rec_supplie_6c621b_idx'), models.Index(fields=['product', 'month_of_supply'], name='website_rec_product_0b0fb1_idx')],
            },
        ),
    ]
