# Generated by Django 5.0.14 on 2025-08-08 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_alter_openinginventorysnapshot_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinginventorysnapshot',
            name='snapshot_date',
            field=models.DateField(db_index=True, help_text='Date of inventory snapshot (shared across scenarios)'),
        ),
    ]
