# Generated by Django 5.0.14 on 2025-08-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_alter_openinginventorysnapshot_snapshot_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryprojectionmodel',
            name='closing_inventory_aud',
            field=models.FloatField(default=0, help_text='Closing inventory value in AUD'),
        ),
        migrations.AlterField(
            model_name='inventoryprojectionmodel',
            name='cogs_aud',
            field=models.FloatField(default=0, help_text='Cost of Goods Sold in AUD'),
        ),
        migrations.AlterField(
            model_name='inventoryprojectionmodel',
            name='opening_inventory_aud',
            field=models.FloatField(default=0, help_text='Opening inventory value in AUD'),
        ),
        migrations.AlterField(
            model_name='inventoryprojectionmodel',
            name='production_aud',
            field=models.FloatField(default=0, help_text='Production value in AUD'),
        ),
        migrations.AlterField(
            model_name='inventoryprojectionmodel',
            name='revenue_aud',
            field=models.FloatField(default=0, help_text='Revenue in AUD'),
        ),
    ]
