# Generated by Django 5.0.14 on 2025-08-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_force_inventory_projection_float_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterdataproductmodel',
            name='customer_data_last_updated',
            field=models.DateTimeField(blank=True, help_text='When customer data was last fetched from PowerBI', null=True),
        ),
        migrations.AddField(
            model_name='masterdataproductmodel',
            name='latest_customer_name',
            field=models.CharField(blank=True, help_text='Latest customer name from PowerBI invoices', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='masterdataproductmodel',
            name='latest_invoice_date',
            field=models.DateField(blank=True, help_text='Date of latest invoice from PowerBI', null=True),
        ),
    ]
