# Generated by Django 5.0.14 on 2025-06-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatedproductionmodel',
            name='product_group',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='masterdataepicorbillofmaterialmodel',
            name='ComponentSeq',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterdataepicorbillofmaterialmodel',
            name='EstimatedScrap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterdataepicorbillofmaterialmodel',
            name='SalvageQtyPer',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
