# Generated by Django 5.0.14 on 2025-07-08 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_calculatedproductionmodel_product_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatedforecast',
            name='cogs_aud',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='aggregatedforecast',
            name='qty',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='aggregatedforecast',
            name='revenue_aud',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='calculatedproductionmodel',
            name='cogs_aud',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='calculatedproductionmodel',
            name='cost_aud',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='calculatedproductionmodel',
            name='price_aud',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='calculatedproductionmodel',
            name='revenue_aud',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='masterdatainventory',
            name='cost_aud',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='smart_forecast_model',
            name='Cost_AUD',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
