# Generated by Django 5.0.14 on 2025-07-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_aggregatedforecast_cogs_aud_aggregatedforecast_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smart_forecast_model',
            name='COGS',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='smart_forecast_model',
            name='Forecasted_Weight_Curr',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
