# Generated by Django 5.0.14 on 2025-07-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_smart_forecast_model_cogs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsitecostmodel',
            name='revenue_cost_aud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
