# Generated by Django 5.0.14 on 2025-07-17 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_calculatedproductionmodel_parent_product_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedPlantConversionModifiersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ConversionModifier', models.FloatField(default=1.0)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.masterdataproductmodel')),
                ('Site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.masterdataplantmodel')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.scenarios')),
            ],
            options={
                'unique_together': {('version', 'Product', 'Site')},
            },
        ),
        migrations.CreateModel(
            name='RevenueConversionModifiersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Region', models.CharField(max_length=250)),
                ('ConversionModifier', models.FloatField(default=1.0)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.masterdataproductmodel')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.scenarios')),
            ],
            options={
                'unique_together': {('version', 'Product', 'Region')},
            },
        ),
    ]
