# Generated by Django 5.0.14 on 2025-07-17 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_fixedplantconversionmodifiersmodel_conversionmodifier_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='revenueconversionmodifiersmodel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='revenueconversionmodifiersmodel',
            name='Site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.masterdataplantmodel'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='revenueconversionmodifiersmodel',
            unique_together={('version', 'Product', 'Site')},
        ),
    ]
