# Generated by Django 5.0.14 on 2025-07-17 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_revenueconversionmodifiersmodel_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueToCogsConversionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GrossMargin', models.FloatField(blank=True, default=0.0, null=True)),
                ('InHouseProduction', models.FloatField(blank=True, default=0.0, null=True)),
                ('CostAUDPerKG', models.FloatField(blank=True, default=0.0, null=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.masterdataproductmodel')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.scenarios')),
            ],
            options={
                'unique_together': {('version', 'Product')},
            },
        ),
        migrations.CreateModel(
            name='SiteAllocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AllocationPercentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.masterdataproductmodel')),
                ('Site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.masterdataplantmodel')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.scenarios')),
            ],
            options={
                'unique_together': {('version', 'Product', 'Site')},
            },
        ),
        migrations.DeleteModel(
            name='RevenueConversionModifiersModel',
        ),
    ]
