# Generated by Django 5.0.14 on 2025-07-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_revenuetocogsconversionmodel_siteallocationmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterDataEpicorMethodOfManufacturingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(blank=True, max_length=50, null=True)),
                ('Plant', models.CharField(blank=True, max_length=50, null=True)),
                ('ProductKey', models.CharField(blank=True, max_length=100, null=True)),
                ('SiteName', models.CharField(blank=True, max_length=100, null=True)),
                ('OperationSequence', models.IntegerField(blank=True, null=True)),
                ('OperationDesc', models.CharField(blank=True, max_length=255, null=True)),
                ('WorkCentre', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'website_masterdataepicormethodofmanufacturingmodel',
                'unique_together': {('Plant', 'ProductKey', 'OperationSequence')},
            },
        ),
    ]
