# Generated by Django 5.0.14 on 2025-07-21 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_masterdataepicormethodofmanufacturingmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterDataSafetyStocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plant', models.CharField(blank=True, max_length=10, null=True)),
                ('PartNum', models.CharField(blank=True, max_length=50, null=True)),
                ('MinimumQty', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('SafetyQty', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.scenarios')),
            ],
            options={
                'db_table': 'MasterDataSafetyStocks',
                'unique_together': {('version', 'Plant', 'PartNum')},
            },
        ),
    ]
