# Generated by Django 5.0.14 on 2025-07-23 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_aggregatedforecastchartdata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedFinancialChartData',
            fields=[
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.scenarios')),
                ('financial_by_group', models.JSONField(default=dict)),
                ('parent_product_groups', models.JSONField(default=list)),
                ('total_revenue_aud', models.FloatField(default=0)),
                ('total_cogs_aud', models.FloatField(default=0)),
                ('total_production_aud', models.FloatField(default=0)),
                ('total_inventory_projection', models.FloatField(default=0)),
                ('revenue_chart_data', models.JSONField(default=dict)),
                ('cogs_chart_data', models.JSONField(default=dict)),
                ('production_chart_data', models.JSONField(default=dict)),
                ('inventory_projection_data', models.JSONField(default=dict)),
                ('combined_financial_data', models.JSONField(default=dict)),
                ('calculation_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
