# Generated by Django 5.0.14 on 2025-07-24 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_add_calculated_fields'),
        ('website', '0019_aggregatedfinancialchartdata'),
    ]

    operations = [
    ]
