# Generated by Django for populating calculated fields

from django.db import migrations
from calendar import monthrange

def populate_calculated_fields(apps, schema_editor):
    """Populate CalendarDays, AvailableDays, and PlanDressMass for existing records."""
    MasterDataPlan = apps.get_model('website', 'MasterDataPlan')
    
    for record in MasterDataPlan.objects.all():
        # Calculate CalendarDays
        if record.Month:
            record.CalendarDays = monthrange(record.Month.year, record.Month.month)[1]
        else:
            record.CalendarDays = 0
            
        # Calculate AvailableDays
        if record.CalendarDays:
            record.AvailableDays = (
                record.CalendarDays
                - (record.PublicHolidays or 0)
                - (record.Weekends or 0)
                - (record.OtherNonPouringDays or 0)
                - (record.PlannedMaintenanceDays or 0)
            )
        else:
            record.AvailableDays = 0
            
        # Calculate PlanDressMass
        if record.AvailableDays and record.heatsperdays and record.TonsPerHeat and record.Yield:
            record.PlanDressMass = (
                record.AvailableDays
                * record.heatsperdays
                * record.TonsPerHeat
                * (record.Yield / 100)  # Convert percentage to decimal
                * (1 - (record.WasterPercentage or 0) / 100)
            )
        else:
            record.PlanDressMass = 0
            
        record.save()

def reverse_populate_calculated_fields(apps, schema_editor):
    """Reverse migration - clear the calculated fields."""
    MasterDataPlan = apps.get_model('website', 'MasterDataPlan')
    MasterDataPlan.objects.update(
        CalendarDays=None,
        AvailableDays=None,
        PlanDressMass=None
    )

class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_merge_20250724_1246'),
    ]

    operations = [
        migrations.RunPython(populate_calculated_fields, reverse_populate_calculated_fields),
    ]
