# Generated by Django 5.0.14 on 2025-07-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_populate_calculated_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdataproductmodel',
            name='ProductGroupDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
