# Generated by Django 5.0.14 on 2025-08-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_alter_masterdataproductmodel_productgroupdescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aggregatedfoundrychartdata',
            name='version',
        ),
        migrations.RemoveField(
            model_name='aggregatedinventorychartdata',
            name='version',
        ),
        migrations.AddField(
            model_name='calcualtedreplenishmentmodel',
            name='latest_customer_invoice',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='calcualtedreplenishmentmodel',
            name='latest_customer_invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calculatedproductionmodel',
            name='latest_customer_invoice',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='calculatedproductionmodel',
            name='latest_customer_invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='AggregatedForecastChartData',
        ),
        migrations.DeleteModel(
            name='AggregatedFoundryChartData',
        ),
        migrations.DeleteModel(
            name='AggregatedInventoryChartData',
        ),
    ]
