# Generated by Django 5.0.14 on 2025-08-06 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_receiptedquantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdatasupplyoptionsmodel',
            name='Site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supply_options', to='website.masterdataplantmodel'),
        ),
        migrations.AlterField(
            model_name='masterdatasupplyoptionsmodel',
            name='Supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supply_options', to='website.masterdatasuppliersmodel'),
        ),
    ]
