# Generated by Django 5.0.14 on 2025-08-06 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_alter_masterdatasupplyoptionsmodel_site_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryProjectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Month for this projection')),
                ('parent_product_group', models.CharField(help_text='Parent Product Group Description', max_length=250)),
                ('product_group', models.CharField(help_text='Product Group Description', max_length=250)),
                ('production_aud', models.DecimalField(decimal_places=2, default=0, help_text='Production value in AUD', max_digits=15)),
                ('cogs_aud', models.DecimalField(decimal_places=2, default=0, help_text='Cost of Goods Sold in AUD', max_digits=15)),
                ('revenue_aud', models.DecimalField(decimal_places=2, default=0, help_text='Revenue in AUD', max_digits=15)),
                ('opening_inventory_aud', models.DecimalField(decimal_places=2, default=0, help_text='Opening inventory value in AUD', max_digits=15)),
                ('closing_inventory_aud', models.DecimalField(decimal_places=2, default=0, help_text='Closing inventory value in AUD', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_projections', to='website.scenarios')),
            ],
            options={
                'ordering': ['version', 'parent_product_group', 'product_group', 'month'],
                'indexes': [models.Index(fields=['version', 'parent_product_group'], name='website_inv_version_dbc97f_idx'), models.Index(fields=['version', 'month'], name='website_inv_version_b56f62_idx')],
                'unique_together': {('version', 'month', 'parent_product_group', 'product_group')},
            },
        ),
    ]
