# Generated by Django 5.0.14 on 2025-08-06 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_clean_inventory_projection_duplicates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryprojectionmodel',
            options={'ordering': ['version', 'parent_product_group', 'month']},
        ),
        migrations.AlterUniqueTogether(
            name='inventoryprojectionmodel',
            unique_together={('version', 'month', 'parent_product_group')},
        ),
        migrations.RemoveField(
            model_name='inventoryprojectionmodel',
            name='product_group',
        ),
    ]
