# Generated by Django 5.0.14 on 2025-08-08 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_remove_product_group_from_inventory_projection'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningInventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True, help_text='Date of inventory snapshot')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this snapshot was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this snapshot was last updated')),
                ('parent_product_group', models.CharField(db_index=True, help_text='Parent product group description', max_length=255)),
                ('inventory_value_aud', models.DecimalField(decimal_places=2, help_text='Opening inventory value in AUD', max_digits=20)),
                ('source_system', models.CharField(default='PowerBI', help_text='Source system (PowerBI, Manual, etc)', max_length=50)),
                ('data_freshness_hours', models.IntegerField(default=0, help_text='How old the source data was when captured')),
                ('refresh_reason', models.CharField(default='auto_upload', help_text='Why this snapshot was refreshed', max_length=100)),
                ('created_by_user', models.CharField(blank=True, help_text='User who triggered the refresh', max_length=100, null=True)),
                ('version', models.ForeignKey(help_text='Scenario version', on_delete=django.db.models.deletion.CASCADE, to='website.scenarios')),
            ],
            options={
                'verbose_name': 'Opening Inventory Snapshot',
                'verbose_name_plural': 'Opening Inventory Snapshots',
                'db_table': 'website_openinginventorysnapshot',
                'ordering': ['version', 'parent_product_group'],
                'indexes': [models.Index(fields=['version', 'snapshot_date'], name='opening_inv_scenario_date_idx'), models.Index(fields=['version', 'parent_product_group'], name='opening_inv_scenario_group_idx'), models.Index(fields=['created_at'], name='opening_inv_created_idx'), models.Index(fields=['snapshot_date', 'created_at'], name='opening_inv_date_created_idx')],
                'unique_together': {('version', 'snapshot_date', 'parent_product_group')},
            },
        ),
    ]
