# Generated by Django 5.0.14 on 2025-08-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_openinginventorysnapshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openinginventorysnapshot',
            options={'ordering': ['snapshot_date', 'parent_product_group'], 'verbose_name': 'Opening Inventory Snapshot', 'verbose_name_plural': 'Opening Inventory Snapshots'},
        ),
        migrations.RemoveIndex(
            model_name='openinginventorysnapshot',
            name='opening_inv_scenario_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='openinginventorysnapshot',
            name='opening_inv_scenario_group_idx',
        ),
        migrations.RemoveIndex(
            model_name='openinginventorysnapshot',
            name='opening_inv_date_created_idx',
        ),
        migrations.AlterUniqueTogether(
            name='openinginventorysnapshot',
            unique_together={('snapshot_date', 'parent_product_group')},
        ),
        migrations.AddField(
            model_name='openinginventorysnapshot',
            name='scenarios_using_this_snapshot',
            field=models.JSONField(default=list, help_text='List of scenario versions using this snapshot'),
        ),
        migrations.AlterField(
            model_name='openinginventorysnapshot',
            name='snapshot_date',
            field=models.DateField(db_index=True, help_text='Date of inventory snapshot (shared across scenarios)', unique=True),
        ),
        migrations.AddIndex(
            model_name='openinginventorysnapshot',
            index=models.Index(fields=['snapshot_date'], name='opening_inv_date_idx'),
        ),
        migrations.AddIndex(
            model_name='openinginventorysnapshot',
            index=models.Index(fields=['parent_product_group'], name='opening_inv_group_idx'),
        ),
        migrations.AddIndex(
            model_name='openinginventorysnapshot',
            index=models.Index(fields=['snapshot_date', 'parent_product_group'], name='opening_inv_date_group_idx'),
        ),
        migrations.RemoveField(
            model_name='openinginventorysnapshot',
            name='version',
        ),
    ]
