# Generated by Django 5.0.14 on 2025-08-09 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_add_customer_fields_to_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPouredDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=250)),
                ('fiscal_year', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('month_year_display', models.CharField(max_length=20)),
                ('monthly_tonnes', models.FloatField(default=0)),
                ('record_count', models.IntegerField(default=0)),
                ('min_date', models.DateField(blank=True, null=True)),
                ('max_date', models.DateField(blank=True, null=True)),
                ('data_fetched_date', models.DateTimeField(auto_now_add=True)),
                ('snapshot_date', models.DateField(help_text='Inventory snapshot date this data was fetched for')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.scenarios')),
            ],
            options={
                'indexes': [models.Index(fields=['version', 'site_name', 'fiscal_year'], name='website_mon_version_fc0053_idx'), models.Index(fields=['version', 'site_name', 'year', 'month'], name='website_mon_version_c4e02a_idx'), models.Index(fields=['snapshot_date'], name='website_mon_snapsho_a2dd14_idx')],
                'unique_together': {('version', 'site_name', 'fiscal_year', 'year', 'month')},
            },
        ),
    ]
