# Generated by Django 5.0.14 on 2025-08-14 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_add_monthly_poured_data_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculatedproductionmodel',
            old_name='cogs_aud',
            new_name='production_aud',
        ),
        migrations.AddField(
            model_name='scenarios',
            name='calculation_status',
            field=models.CharField(choices=[('never_calculated', 'Never Calculated'), ('up_to_date', 'Up to Date'), ('changes_detected', 'Changes Detected - Recalculation Needed'), ('calculating', 'Currently Calculating'), ('calculation_failed', 'Calculation Failed')], default='never_calculated', help_text='Current calculation status', max_length=50),
        ),
        migrations.AddField(
            model_name='scenarios',
            name='last_calculated',
            field=models.DateTimeField(blank=True, help_text='When calculate_model was last run successfully', null=True),
        ),
    ]
