# Generated by Django 5.0.14 on 2025-08-10 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_add_monthly_poured_data_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculatedproductionmodel',
            old_name='cogs_aud',
            new_name='production_aud',
        ),
        migrations.CreateModel(
            name='ProductionAllocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.CharField(help_text="Format: 'Jul-25', 'Aug-25', etc.", max_length=10)),
                ('allocation_percentage', models.FloatField(default=0.0, help_text='Percentage of total production (0-100)')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='Product to allocate', on_delete=django.db.models.deletion.CASCADE, to='website.masterdataproductmodel')),
                ('site', models.ForeignKey(help_text='Site to allocate to', on_delete=django.db.models.deletion.CASCADE, to='website.masterdataplantmodel')),
                ('version', models.ForeignKey(help_text='Scenario version', on_delete=django.db.models.deletion.CASCADE, to='website.scenarios')),
            ],
            options={
                'verbose_name': 'Production Allocation',
                'verbose_name_plural': 'Production Allocations',
                'unique_together': {('version', 'product', 'site', 'month_year')},
            },
        ),
    ]
