# Generated by Django 5.0.14 on 2025-08-15 00:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_rename_cogs_aud_calculatedproductionmodel_production_aud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterdatafreightmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masterdatafreightmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='masterdataorderbook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masterdataorderbook',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='masterdatasafetystocks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masterdatasafetystocks',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='revenue_forecast_model',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revenue_forecast_model',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='smart_forecast_model',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smart_forecast_model',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ProductionAllocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.CharField(help_text="Format: 'Jul-25', 'Aug-25', etc.", max_length=10)),
                ('allocation_percentage', models.FloatField(default=0.0, help_text='Percentage of total production (0-100)')),
                ('product_code', models.CharField(blank=True, help_text='Product code for search/filter', max_length=250, null=True)),
                ('product_description', models.CharField(blank=True, help_text='Product description for search/filter', max_length=500, null=True)),
                ('product', models.ForeignKey(help_text='Product to allocate', on_delete=django.db.models.deletion.CASCADE, to='website.masterdataproductmodel')),
                ('site', models.ForeignKey(help_text='Site to allocate to', on_delete=django.db.models.deletion.CASCADE, to='website.masterdataplantmodel')),
                ('version', models.ForeignKey(help_text='Scenario version', on_delete=django.db.models.deletion.CASCADE, to='website.scenarios')),
            ],
            options={
                'verbose_name': 'Production Allocation',
                'verbose_name_plural': 'Production Allocations',
                'unique_together': {('version', 'product', 'site', 'month_year')},
            },
        ),
    ]
