# Generated by Django 5.0.14 on 2025-08-16 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_create_production_allocation_model_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterdatamanuallyassignproductionrequirement',
            name='Percentage',
        ),
        migrations.RemoveField(
            model_name='masterdatamanuallyassignproductionrequirement',
            name='ShippingDate',
        ),
    ]
