# Generated by Django 5.0.14 on 2025-08-16 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0042_remove_masterdatamanuallyassignproductionrequirement_percentage_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='masterdatamanuallyassignproductionrequirement',
            unique_together={('Product', 'version')},
        ),
    ]
